<robot name="my_laser" xmlns:xacro="http://wiki.ros.org/xacro">

    <material name="orange">
        <color rgba="1.0 0.5 0.2 1" />
    </material>
    <material name="gray">
        <color rgba="0.2 0.2 0.2 1" />
    </material>

    <link name="imu_link">
        <visual>
        <origin xyz="0 0 0" />
        <geometry>
            <!--box size="0.034 0.034 0.016" /-->
            <box size="0.0 0.0 0.0" />
        </geometry>
        <material name="orange" />
        </visual>
    </link>

    <joint name="imu_link_joint" type="fixed">
        <parent link="base_link" />
        <child link="imu_link" />
        <origin xyz="0 0 0"/>
    </joint>

    <!-- 雷达 -->
    <!-- 雷达属性 -->
    <xacro:property name="laser_length" value="0.0935" /> <!-- 高度 -->
    <xacro:property name="laser_radius" value="0.04447" /> <!-- 半径 -->
    
    <xacro:macro name="add_lasers" params="name flag">
        <link name="laser_wj${name}">
            <visual>
            <origin xyz="0 0 0" />
            <geometry>
                <cylinder length="${laser_length}" radius="${laser_radius}" />
            </geometry>
            <material name="gray" />
            </visual>
        </link>
 
        <joint name="laser${name}2base_link" type="fixed">
            <parent link="base_link" />
            <child link="laser_wj${name}" />
            <!-- y轴配准的话，2号laser y轴要多0.05 z=底盘高度/2+雷达高度/2 -->
            <origin rpy="0 0 ${-(flag-1)*PI/2}" xyz="${flag*base_link_length/2} ${flag*base_link_width/2} ${base_link_height/2+earth_space/2}" />
        </joint>
    </xacro:macro>

    <xacro:add_lasers name="_1" flag="-1" />
    <xacro:add_lasers name="_2" flag="1" />

</robot>