<robot name="my_laser" xmlns:xacro="http://wiki.ros.org/xacro">

    <!-- 相机支架属性 -->
    <xacro:property name="support_length" value="0.22" /> <!-- 支架长度 -->
    <xacro:property name="support_radius" value="0.01" /> <!-- 支架半径 -->
    <xacro:property name="support_x" value="0.105" /> <!-- 支架安装的x坐标 -->
    <xacro:property name="support_y" value="0.0" /> <!-- 支架安装的y坐标 -->
    <xacro:property name="support_z" value="${base_link_height/2 + earth_space + support_length/2}" /> <!-- 支架安装的z坐标:底盘高度 / 2 + 支架高度 / 2  -->
 
    <link name="support">
        <visual>
            <geometry>
                <cylinder radius="${support_radius}" length="${support_length}" />
            </geometry>
            <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0" />
            <material name="white">
                <color rgba="1 1 1 0.8" />
            </material>
        </visual>
    </link>
 
    <joint name="support2base_link" type="fixed">
        <parent link="base_link" />
        <child link="support" />
        <origin xyz="${support_x} ${support_y} ${support_z}" />
    </joint>


    <xacro:property name="camera_length" value="0.023" />
    <xacro:property name="camera_width" value="0.07" />
    <xacro:property name="camera_height" value="0.01" />
    <xacro:property name="camera_x" value="0.0" />
    <xacro:property name="camera_y" value="0.0" />
    <xacro:property name="camera_z" value="${support_length/2}" />

    <!-- 相机属性 -->
    <link name="camera">
        <visual>
            <geometry>
                <box size="${camera_length} ${camera_width} ${camera_height}" />
            </geometry>
            <origin xyz="0 0 0" rpy="0 0 0" />
            <material name="blue">
                <color rgba="0.3 0.9 1.0 0.8" />
            </material>
        </visual>
    </link>

    <joint name="camera2support" type="fixed">
        <parent link="support" />
        <child link="camera" />
        <origin xyz="${camera_x} ${camera_y} ${camera_z}" />
    </joint>

</robot>