<robot name="my_base" xmlns:xacro="http://www.ros.org/wiki/xacro">
    <!-- PI 值设置 -->
    <xacro:property name="PI" value="3.1415926" />
    <!-- 宏:黑色设置 -->
    <material name="black">
        <color rgba="0.0 0.0 0.0 1.0" />
    </material>
    <!-- 底盘属性 -->
    <!-- <xacro:property name="base_footprint_radius" value="0.001" /> -->
    <xacro:property name="base_link_length" value="0.55" /> <!-- base_link 长 -->
    <xacro:property name="base_link_width" value="0.44" /> <!-- base_link 宽 -->
    <xacro:property name="base_link_height" value="0.21" /> <!-- base_link 高 -->
    <xacro:property name="earth_space" value="0.09" /> <!-- 底盘离地间距 -->
 
    <!-- <link name="base_footprint">
        <visual>
            <geometry>
                <sphere radius="${base_footprint_radius}" />
            </geometry>
        </visual>
    </link> -->
 
    <link name="base_link">
        <visual>
            <geometry>
                <box size="${base_link_length} ${base_link_width} ${base_link_height}" />
            </geometry>
            <origin xyz="0 0 ${earth_space}" rpy="0 0 0" />
            <material name="yellow">
                <color rgba="0.5 0.3 0.0 0.5" />
            </material>
        </visual>
    </link>

 
    <!-- <joint name="base_link2base_footprint" type="fixed">
        <parent link="base_footprint" />
        <child link="base_link" />
        <origin xyz="0 0 ${earth_space + base_link_height / 2 }" />
    </joint> -->

    <!-- direction link 一个红色的圆盘指示小车车头的方向 -->
    <link name="dir_link">
        <visual>
            <geometry>
                <cylinder length="0.01" radius="0.05" />
            </geometry>
        </visual>
    </link>

    <joint name="dir2base_link" type="fixed">
        <parent link="base_link" />
        <child link="dir_link" />
        <origin xyz="0.1 0 ${earth_space + base_link_height / 2 }" />
    </joint>
 
    <!-- 驱动轮 -->
    <xacro:property name="wheel_radius" value="0.085" /> <!-- 半径 -->
    <xacro:property name="wheel_length" value="0.045" /> <!-- 宽度 -->
 
    <!-- 驱动轮宏实现 -->
    <xacro:macro name="add_wheels" params="name flag">
        <link name="${name}_wheel">
            <visual>
                <geometry>
                    <cylinder radius="${wheel_radius}" length="${wheel_length}" />
                </geometry>
                <origin xyz="0.0 0.0 0.0" rpy="${PI / 2} 0.0 0.0" />
                <material name="black" />
            </visual>
        </link>
 
        <joint name="${name}_wheel2base_link" type="fixed">
            <parent link="base_link" />
            <child link="${name}_wheel" />
            <origin xyz="0 ${flag * (base_link_width/2+wheel_length/2)} ${-(earth_space + base_link_height / 2 - wheel_radius) }" />
            <axis xyz="0 1 0" />
        </joint>
    </xacro:macro>
    
    <!-- <xacro:add_wheels name="left" flag="1" />
    <xacro:add_wheels name="right" flag="-1" /> -->
 
    <!-- 支撑轮 -->
    <xacro:property name="support_wheel_radius" value="0.03" /> <!-- 支撑轮半径 -->
 
    <!-- 支撑轮宏 -->
    <xacro:macro name="add_support_wheel" params="name flag1 flag2">
        <link name="${name}_wheel">
            <visual>
                <geometry>
                    <sphere radius="${support_wheel_radius}" />
                </geometry>
                <origin xyz="0 0 0" rpy="0 0 0" />
                <material name="black" />
            </visual>
        </link>
 
        <joint name="${name}_wheel2base_link" type="continuous">
            <parent link="base_link" />
            <child link="${name}_wheel" />
            <origin xyz="${flag1 * (base_link_length/2 - support_wheel_radius)} ${flag2 * (base_link_width/2 - support_wheel_radius)} ${-(base_link_height / 2 + earth_space-support_wheel_radius)}" />
            <axis xyz="1 1 1" />
        </joint>
    </xacro:macro>
 
    <!-- <xacro:add_support_wheel name="front_left" flag1="1" flag2="1"/>
    <xacro:add_support_wheel name="front_right" flag1="1" flag2="-1"/>
    <xacro:add_support_wheel name="back_left" flag1="-1" flag2="1"/>
    <xacro:add_support_wheel name="back_right" flag1="-1" flag2="-1"/> -->
 
</robot>
